// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDllwsiOKESJ_Y0NDvN_a0vCixXBC7mlZ4',
    appId: '1:341040915422:web:ec971b1e14606654e0b34f',
    messagingSenderId: '341040915422',
    projectId: 'fateen1',
    authDomain: 'fateen1.firebaseapp.com',
    storageBucket: 'fateen1.firebasestorage.app',
    measurementId: 'G-6XCMXSVDDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfxOhWCKJSDXFd5BNnr7kjNee_bI1TAxg',
    appId: '1:341040915422:android:ee16713d3814a792e0b34f',
    messagingSenderId: '341040915422',
    projectId: 'fateen1',
    storageBucket: 'fateen1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLvn0eBUJCDKD2zOhvD_hUum0nqYC7hgI',
    appId: '1:341040915422:ios:35682b11cc889822e0b34f',
    messagingSenderId: '341040915422',
    projectId: 'fateen1',
    storageBucket: 'fateen1.firebasestorage.app',
    iosBundleId: 'com.examfple.fateen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLvn0eBUJCDKD2zOhvD_hUum0nqYC7hgI',
    appId: '1:341040915422:ios:590055af8befe7a2e0b34f',
    messagingSenderId: '341040915422',
    projectId: 'fateen1',
    storageBucket: 'fateen1.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDllwsiOKESJ_Y0NDvN_a0vCixXBC7mlZ4',
    appId: '1:341040915422:web:de98fefd321f99c2e0b34f',
    messagingSenderId: '341040915422',
    projectId: 'fateen1',
    authDomain: 'fateen1.firebaseapp.com',
    storageBucket: 'fateen1.firebasestorage.app',
    measurementId: 'G-JG5GYX45VK',
  );
}
