// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqbnyC01-1MgP8n0Pz0TWAoQ1pn9Yd4uw',
    appId: '1:381666460426:web:bde03f3c9b45b4a9bf30f3',
    messagingSenderId: '381666460426',
    projectId: 'fateen-17a39',
    authDomain: 'fateen-17a39.firebaseapp.com',
    storageBucket: 'fateen-17a39.firebasestorage.app',
    measurementId: 'G-0BS2PS7512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU996YH7gi9BoST8PYXIm5eX0QXDpAsC4',
    appId: '1:381666460426:android:0331993465c2eb6fbf30f3',
    messagingSenderId: '381666460426',
    projectId: 'fateen-17a39',
    storageBucket: 'fateen-17a39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PRHJYpUukBRgtSC9E0qro0HOCeLy_dM',
    appId: '1:381666460426:ios:c74599b0c260222dbf30f3',
    messagingSenderId: '381666460426',
    projectId: 'fateen-17a39',
    storageBucket: 'fateen-17a39.firebasestorage.app',
    iosBundleId: 'com.examfple.fateen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PRHJYpUukBRgtSC9E0qro0HOCeLy_dM',
    appId: '1:381666460426:ios:9789de9ec98de071bf30f3',
    messagingSenderId: '381666460426',
    projectId: 'fateen-17a39',
    storageBucket: 'fateen-17a39.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqbnyC01-1MgP8n0Pz0TWAoQ1pn9Yd4uw',
    appId: '1:381666460426:web:1ccae08e982b7bf1bf30f3',
    messagingSenderId: '381666460426',
    projectId: 'fateen-17a39',
    authDomain: 'fateen-17a39.firebaseapp.com',
    storageBucket: 'fateen-17a39.firebasestorage.app',
    measurementId: 'G-DMG5023LJZ',
  );
}
